title: Everett Green - Senior E-commerce Engineer
author:
  name: Everett Green
metadata:
    description: 'The personal website and CV of Everett Green, Senior E-commerce Engineer, Certified Salesforce B2C Commerce Cloud Developer'

# Header customization
header:
  title: I'm Everett Green.
  description: I'm a Knoxville, TN-based <span>Senior E-commerce Engineer</span>. I am a <span>Senior SFCC Developer</span> for Conair LLC, the manufacturer of Conair, Cuisinart, and other popular brands. Let's <a class="smoothscroll" href="#about">start scrolling</a> and learn more <a class="smoothscroll" href="#about">about me</a>.
copyright:
    - line: &copy; Copyright 2024 Everett Green
    - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>
social:
- url: "https://www.facebook.com/everett.green"
  icon: facebook
- url: "https://twitter.com/everettgreen"
  icon: twitter
- url: "https://www.linkedin.com/in/everettkgreen"
  icon: linkedin

