home:
  alias: '/home'

pages:
  theme: everett-green-ceevee
  process:
    markdown: true
    twig: true
  markdown:
    extra: true

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true

strict_mode:
  yaml_compat: true
  twig_compat: true
  blueprint_compat: true
